# ---------------------------------------------------------------------------------
# ---------------------------- CONFIGURATION --------------------------------------
# ---------------------------------------------------------------------------------
BASE_NAMES = REDIS
# DOCKERHUB_BASE_NAMES = PGBOUNCER POSTGRES
PORTFORWARD = REDIS
ROLLING_DEPLOYMENTS = REDIS

# Default credentials (injectable via command line)
REDIS_PASS ?= redissecret
AWS_KEY_ID ?= AKIAX7SUEXAT7OWTXRLH
AWS_SECRET_KEY ?= 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
AWS_REGION ?= eu-central-1
ECR_URL ?= 548858542119.dkr.ecr.eu-central-1.amazonaws.com

#################################################################3
#make bootstrap
#make deploy-app
#make calculate-resources

# ---------------------------------------------------------------------------------
# ---------------------------- AWS & BASE IMAGES ----------------------------------
# ---------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------
# ---------------------------- AWS & BASE IMAGES ----------------------------------
# ---------------------------------------------------------------------------------
aws-login:
	@echo "======================= CONFIGURING AWS CLI =========================="
	@aws configure set aws_access_key_id "$(AWS_KEY_ID)"; \
	aws configure set aws_secret_access_key "$(AWS_SECRET_KEY)"; \
	aws configure set region "$(AWS_REGION)";
	@echo "======================= LOGGING IN TO AWS ECR =========================="
	@aws ecr get-login-password --region $(AWS_REGION) | \
	docker login --username AWS --password-stdin "$(ECR_URL)"

base-build:
	@echo "----------------- Starting port-forward to local registry -------------------"
	@kubectl port-forward svc/registry 5000:5000 > /dev/null 2>&1 &
	@echo "Waiting for port-forward..." && sleep 5

	@echo "----------------- Pulling, Tagging, and Pushing Base Images -------------------"
	@# These variables are now read from the ConfigMaps generated by Helm
	@IMG_PREFIX="tis"; \
	ENV_TAG="prd"; \
	BITBUCKET_BRANCH="master"; \
	AWS_ECR_REGISTRY_URL="$(ECR_URL)"; \
	for base_name in $(BASE_NAMES); do \
    		config_map=$$(echo $$base_name | tr 'A-Z' 'a-z')-config; \
    		\
    		echo "Reading metadata from ConfigMap: $$config_map"; \
    		IMAGE_NAME=$$(kubectl get configmap $$config_map -o jsonpath="{.data.$${base_name}_IMAGE}"); \
    		VERSION=$$(kubectl get configmap $$config_map -o jsonpath="{.data.$${base_name}_VERSION}"); \
    		LOCAL_TAG=$$(kubectl get configmap $$config_map -o jsonpath="{.data.$${base_name}_BUILT_IMAGE}"); \
    		\
    		ECR_IMAGE_PATH="$${AWS_ECR_REGISTRY_URL}/$${IMG_PREFIX}-$${IMAGE_NAME}:$${ENV_TAG}-$${BITBUCKET_BRANCH}-$${VERSION}"; \
    		LOCAL_IMAGE_PATH="localhost:5000/$${LOCAL_TAG}"; \
    		\
    		echo "--- Processing service: $$base_name ---"; \
    		echo "Pulling from: $${ECR_IMAGE_PATH}"; \
    		docker pull "$${ECR_IMAGE_PATH}"; \
    		echo "Tagging as: $${LOCAL_IMAGE_PATH}"; \
    		docker tag "$${ECR_IMAGE_PATH}" "$${LOCAL_IMAGE_PATH}"; \
    		docker push "$${LOCAL_IMAGE_PATH}"; \
    		echo "--- Done ---"; \
    	done

	@echo "----------------- Pulling, Tagging, and Pushing Docker Hub Base Images -------------------"
	@for base_name in $(DOCKERHUB_BASE_NAMES); do \
			config_map=$$(echo $$base_name | tr 'A-Z' 'a-z')-config; \
			\
			echo "Reading metadata from ConfigMap: $$config_map"; \
			DOCKERHUB_IMAGE_PATH=$$(kubectl get configmap $$config_map -o jsonpath="{.data.$${base_name}_IMAGE}"); \
			LOCAL_TAG=$$(kubectl get configmap $$config_map -o jsonpath="{.data.$${base_name}_BUILT_IMAGE}"); \
			LOCAL_IMAGE_PATH="localhost:5000/$${LOCAL_TAG}"; \
			\
			echo "--- Processing Docker Hub service: $$base_name ---"; \
			echo "Pulling from: $${DOCKERHUB_IMAGE_PATH}"; \
			docker pull "$${DOCKERHUB_IMAGE_PATH}"; \
			echo "Tagging as: $${LOCAL_IMAGE_PATH}"; \
			docker tag "$${DOCKERHUB_IMAGE_PATH}" "$${LOCAL_IMAGE_PATH}"; \
			docker push "$${LOCAL_IMAGE_PATH}"; \
			echo "--- Done ---"; \
		done

	@echo "----------------- Verifying images in local registry -------------------"
	@curl -s http://localhost:5000/v2/_catalog
	@echo "----------------- Killing port-forward process -------------------"
	@fuser -k 5000/tcp > /dev/null 2>&1 || true


# ---------------------------------------------------------------------------------
# ------------------------------ MINIKUBE MANAGEMENT ------------------------------
# ---------------------------------------------------------------------------------
mk-up:
	@echo "----------------- Starting Minikube -------------------"
	minikube start --insecure-registry="192.168.0.0/16" --force
	minikube config set insecure-registry "registry.default.svc.cluster.local:5000"
	minikube config set insecure-registry "localhost:5000"

mk-setup:
	@echo "----------------- Mounting working directory into Minikube -------------------"
	@# We mount the current directory to /workspace so Kaniko can see docker/redis
	docker cp . minikube:/workspace

mk-delete:
	-minikube delete

# ---------------------------------------------------------------------------------
# -------------------------------- OPS / VERIFY -----------------------------------
# ---------------------------------------------------------------------------------

verify-builds:
	@chmod +x scripts/verify-builds.sh
	@bash scripts/verify-builds.sh

test-system:
	@chmod +x scripts/test-system.sh
	@bash scripts/test-system.sh

calculate-resources:
	@chmod +x scripts/calculate-resources.sh
	@bash scripts/calculate-resources.sh
	@make rollout-restart
	@make checking-vars

checking-vars:
	@chmod +x scripts/checking-vars.sh
	@bash scripts/checking-vars.sh

# ---------------------------------------------------------------------------------
# ----------------------------------- BOOTSTRAP -----------------------------------
# ---------------------------------------------------------------------------------
infra-setup:
	@echo "----------------- Applying Infrastructure (Registry) -------------------"
	kubectl apply -f infra/registry.yaml
	kubectl rollout status deployment registry -n default --timeout=180s

# The main entry point
bootstrap: mk-delete mk-up mk-setup infra-setup helm-install-config aws-login base-build build-k8s-redis
	@echo "==========================================================="
	@echo "🎉 Redis System bootstrapped successfully!"
	@echo "==========================================================="
	@echo ""
	@make verify-builds

# ---------------------------------------------------------------------------------
# ----------------------------------- HELM DEPLOY ---------------------------------
# ---------------------------------------------------------------------------------
helm-install-config:
	@echo "----------------- Deploying TIS Stack CONFIG ONLY -------------------"
	@MINIKUBE_IP=$$(minikube ip); \
	helm upgrade --install tis-stack ./charts/tis-stack \
		--namespace default \
		--set global.registry="$$MINIKUBE_IP:30500" \
		--set global.aws.accessKeyId="$(AWS_KEY_ID)" \
		--set global.aws.secretAccessKey="$(AWS_SECRET_KEY)" \
		--set redis.auth.password="$(REDIS_PASS)" \
		--set global.onlyConfig=true

deploy-app:
	@echo "----------------- Enabling TIS Stack DEPLOYMENTS -------------------"
	@helm upgrade tis-stack ./charts/tis-stack \
		--namespace default \
		--reuse-values \
		--set global.onlyConfig=false
	@make rollout-restart

helm-uninstall:
	helm uninstall tis-stack || true

helm-template:
	@echo "----------------- Debugging Helm Templates -------------------"
	helm template tis-stack ./charts/tis-stack --debug

# ---------------------------------------------------------------------------------
# ----------------------------------- BUILD JOBS ----------------------------------
# ---------------------------------------------------------------------------------
build-k8s-redis:
	@echo "----------------- Building Redis for Kubernetes -------------------"
	@kubectl delete job redis-build --ignore-not-found=true

	@kubectl apply -f build/redis/build-job.yaml

	@echo "Waiting for Redis build job..."
	@kubectl wait --for=condition=complete job/redis-build --timeout=180s || \
		(echo "!!! Redis build failed logs: !!!" && kubectl logs job/redis-build --follow && exit 1)
	@echo "Redis build completed."

# ---------------------------------------------------------------------------------
# ----------------------------------- UTILS ---------------------------------------
# ---------------------------------------------------------------------------------

rollout-restart:
	@echo "----------------- Restarting deployments (via ownerReferences) -------------------"
	@for base_name in $(ROLLING_DEPLOYMENTS); do \
		svc=$$(echo $$base_name | tr 'A-Z' 'a-z'); \
		selector="app.kubernetes.io/component=$$svc"; \
		pod=$$(kubectl get pod -l $$selector -o jsonpath='{.items[0].metadata.name}' 2>/dev/null || true); \
		if [ -z "$$pod" ]; then \
			echo "❌ No pod found for $$base_name (selector: $$selector)"; \
		else \
			echo "→ 1 Found pod for $$base_name: $$pod"; \
			rs=$$(kubectl get pod $$pod -o jsonpath='{.metadata.ownerReferences[0].name}' 2>/dev/null || true); \
			if [ -z "$$rs" ]; then \
				echo "❌ No ReplicaSet owner found for pod $$pod"; \
			else \
				echo "   ↳ ReplicaSet: $$rs"; \
				deploy=$$(kubectl get rs $$rs -o jsonpath='{.metadata.ownerReferences[0].name}' 2>/dev/null || true); \
				if [ -z "$$deploy" ]; then \
					echo "❌ No Deployment owner found for ReplicaSet $$rs"; \
				else \
					echo "   ↳ Deployment: $$deploy"; \
					echo "--- Rolling out restart for $$deploy ---"; \
					kubectl rollout restart deployment $$deploy; \
					echo "Waiting for rollouts..."; \
					kubectl rollout status deployment $$deploy; \
				fi; \
			fi; \
		fi; \
	done
	@make wait-for-ready
	@make test-system

wait-for-ready:
	@echo "----------------- Waiting for all pods to be Ready -------------------"
	@for base_name in $(ROLLING_DEPLOYMENTS); do \
		svc=$$(echo $$base_name | tr 'A-Z' 'a-z'); \
		selector="app.kubernetes.io/component=$$svc"; \
		echo "→ Waiting for pods with selector: $$selector"; \
		kubectl wait --for=condition=Ready pod -l $$selector --timeout=120s || exit 1; \
	done

port-forward-services:
	@echo "----------------- Starting port-forwards... -------------------"
	@-pkill -f "kubectl port-forward" || true
	@sleep 2
	@# Reads from redis-config ConfigMap (Metadata)
	@PORT=$$(kubectl get configmap redis-config -o jsonpath="{.data.REDIS_PORT}"); \
	REDIRECT_PORT=$$(kubectl get configmap redis-config -o jsonpath="{.data.REDIS_REDIRECT_PORT}"); \
	nohup kubectl port-forward svc/redis "$${REDIRECT_PORT}:$${PORT}" > /dev/null 2>&1 & \
	echo "    DONE: localhost:$${REDIRECT_PORT} -> svc/redis:$${PORT}";

# ---------------------------------------------------------------------------------
# ----------------------------------- UTILS ---------------------------------------
# ---------------------------------------------------------------------------------


