#!/bin/bash
# INTENT:
#   Exit immediately if any command exits with a non-zero status.
# WHY:
#   In a verification script, any failure (network, missing key, 404) indicates
#   an invalid state. We must not proceed to subsequent checks if the environment is unstable.
set -e

echo "==============================================="
echo "📦 BUILD VERIFICATION (Registry Check)"
echo "==============================================="

# Get Registry URL (Minikube IP : NodePort 30500)
# PURPOSE:
#   Dynamically resolve the internal registry address accessible from the host.
# WHY:
#   We cannot use 'localhost' blindly because Minikube might be running in a VM
#   (driver=hyperkit/kvm) where the IP differs from the host.
#   NodePort 30500 is the fixed entry point defined in infra/registry.yaml.
REGISTRY_IP=$(minikube ip)
REGISTRY_PORT="30500"
REGISTRY_URL="http://$REGISTRY_IP:$REGISTRY_PORT"

echo "Using Registry at: $REGISTRY_URL"

# 1. Fetch Catalog (List of all repositories)
echo -n "🔍 Fetching image catalog... "
# INTENT:
#   Smoke test the registry connectivity before checking specific images.
# TRADE-OFF:
#   We use a short timeout (5s) to fail fast if the registry pod is down or
#   network rules block access to the NodePort.
CATALOG=$(curl -s --connect-timeout 5 "$REGISTRY_URL/v2/_catalog")

if [ -z "$CATALOG" ]; then
    echo "❌ FAILED TO CONNECT TO REGISTRY!"
    echo "   Ensure Minikube is running and Registry NodePort (30500) is open."
    exit 1
fi
echo "✅ OK"

check_redis() {
  echo "==============================================="
  echo "CHECKING REDIS"
  echo "==============================================="

  # INTENT:
  #   Retrieve the expected repository name from the cluster configuration.
  # WHY:
  #   This adheres to the "Single Source of Truth" principle. We rely on the
  #   ConfigMap generated by Helm rather than hardcoding "tis-redis" in this test.
  #   If the Helm chart changes the repo name, this test automatically adapts.
  REPO_NAME=$(kubectl get configmap redis-config -o jsonpath='{.data.REDIS_REPOSITORY}')

  if [ -z "$REPO_NAME" ]; then
      echo "❌ ERROR: Could not read REPO_NAME from 'redis-config' ConfigMap."
      exit 1
  fi

  # TRADE-OFF:
  #   Using `grep` is brittle compared to `jq`, but it avoids adding `jq` as a
  #   hard dependency for the developer's machine.
  if echo "$CATALOG" | grep -Fq "$REPO_NAME"; then
      echo "✅ FOUND: $REPO_NAME"
  else
      echo "❌ MISSING!"
      echo "   Expected: $REPO_NAME"
      echo "   Found in registry: $CATALOG"
      exit 1
  fi
}

check_redis

echo "==============================================="
echo "🎉 ALL BUILDS VERIFIED SUCCESSFULLY"
echo "==============================================="
